// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {config} from '../models';

export function GetActivity():Promise<Array<main.ActivityEntry>>;

export function GetConfig():Promise<config.Config>;

export function IsRunning():Promise<boolean>;

export function Quit():Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function StartBridge():Promise<void>;

export function StopBridge():Promise<void>;
