// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetActivity() {
  return window['go']['main']['App']['GetActivity']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartBridge() {
  return window['go']['main']['App']['StartBridge']();
}

export function StopBridge() {
  return window['go']['main']['App']['StopBridge']();
}
